CASTOR-496: Implement 'None' method.
Contains full TDD cycle to implement the 'None' method.  This method
always returns 'Token' as the message signing token, and always returns
'None' as the signature.  Verification just checks to see if the
signature is 'None'.

Negative tests are still to come.

Also implemented the initial test harness.

diff --git a/libsspl_sec/Makefile.am b/libsspl_sec/Makefile.am
--- a/libsspl_sec/Makefile.am
+++ b/libsspl_sec/Makefile.am
@@ -1,3 +1,34 @@
 AUTOMAKE_OPTIONS=foreign
-SUBDIRS=libsspl_sec doc
+SUBDIRS=libsspl_sec doc tests
+STYLECHECKER=$(ASTYLE) --style=ansi --attach-extern-c --indent-classes --indent-switches --break-blocks --pad-oper --pad-header --unpad-paren --align-pointer=type --remove-brackets --convert-tabs --max-code-length=80  --lineend=linux | head -n-1
+
+check-local: c_style python_style
+
+python_style:
+	$(FLAKE8) .
+	$(PYLINT) ./tests/acceptance/steps/*.py
+
+c_style:
+	@echo ">>> $(STYLECHECKER) <<<"
+	@rm -f stylecheck.tmp
+	@for file in `find . -name '*.h' -or -name '*.c'` ; do \
+		cat $$file | $(STYLECHECKER) > stylecheck.tmp ; \
+		if ! diff -q $$file stylecheck.tmp > /dev/null ; then \
+			echo "ERROR $$file failed style check." ; \
+			echo "Hint: vimdiff $$file stylecheck.tmp" ; \
+			exit 1 ; \
+		fi ; \
+	done
+
+c_style_interactive:
+	@rm -f stylecheck.tmp
+	@for file in `find . -name '*.h' -or -name '*.c'` ; do \
+		cat $$file | $(STYLECHECKER) > stylecheck.tmp ; \
+		if ! diff -q $$file stylecheck.tmp > /dev/null ; then \
+			vimdiff $$file stylecheck.tmp ; \
+		fi ; \
+	done
+
+clean-local:
+	rm -f stylecheck.tmp
 
