EOS-7750 SSPL: Change product name from eos to cortx
- renamed eos to cortx
- moved product name references to common files.

Change-Id: I1ce7173855382833520e8e94df06e3a553c7b638

diff --git a/low-level/files/opt/seagate/sspl/bin/rabbitmq_setup b/low-level/files/opt/seagate/sspl/bin/rabbitmq_setup
--- a/low-level/files/opt/seagate/sspl/bin/rabbitmq_setup
+++ b/low-level/files/opt/seagate/sspl/bin/rabbitmq_setup
@@ -23,17 +23,12 @@ if [ "$status" = "false" ]; then
     systemctl start rabbitmq-server
 fi
 
-# Get product
-product=$(sed -nr 's/^product=([^,]+)$/\1/p' $SSPL_CONF | head -1)
-[ -z "$product" ] && echo "No product specified in $SSPL_CONF" && exit 1
-
 # Add required user and vhost to RabbitMQ. Set user permissions etc.
 echo "Creating required RABBITMQ configuration.... "
-#/opt/seagate/eos/sspl/low-level/framework/sspl_rabbitmq_reinit $product || {
-/opt/seagate/eos/sspl/bin/sspl_rabbitmq_reinit $product || {
+/opt/seagate/$PRODUCT/sspl/bin/sspl_rabbitmq_reinit $PRODUCT || {
     reinit_err="$?";
-    echo -n "/opt/seagate/eos/sspl/bin/sspl_rabbitmq_reinit failed ";
-    echo "with exit code ${reinit_err} for product $product";
+    echo -n "/opt/seagate/$PRODUCT/sspl/bin/sspl_rabbitmq_reinit failed ";
+    echo "with exit code ${reinit_err} for product $PRODUCT";
     exit 1;
 }
 
