EOS-1119 sspl binary format.
Change-Id: I780531920402ca4cffee7e91bc174991481437a6

diff --git a/low-level/files/opt/seagate/sspl/bin/rabbitmq_setup b/low-level/files/opt/seagate/sspl/bin/rabbitmq_setup
--- a/low-level/files/opt/seagate/sspl/bin/rabbitmq_setup
+++ b/low-level/files/opt/seagate/sspl/bin/rabbitmq_setup
@@ -34,9 +34,10 @@ product=$(sed -nr 's/^product=([^,]+)$/\1/p' $SSPL_CONF | head -1)
 
 # Add required user and vhost to RabbitMQ. Set user permissions etc.
 echo "Creating required RABBITMQ configuration.... "
-/opt/seagate/sspl/low-level/framework/sspl_rabbitmq_reinit $product || {
+#/opt/seagate/sspl/low-level/framework/sspl_rabbitmq_reinit $product || {
+/opt/seagate/sspl/bin/sspl_rabbitmq_reinit $product || {
     reinit_err="$?";
-    echo -n "/opt/seagate/sspl/low-level/framework/sspl_rabbitmq_reinit failed ";
+    echo -n "/opt/seagate/sspl/bin/sspl_rabbitmq_reinit failed ";
     echo "with exit code ${reinit_err} for product $product";
     exit 1;
 }
diff --git a/low-level/files/opt/seagate/sspl/bin/sspl_config b/low-level/files/opt/seagate/sspl/bin/sspl_config
--- a/low-level/files/opt/seagate/sspl/bin/sspl_config
+++ b/low-level/files/opt/seagate/sspl/bin/sspl_config
@@ -15,7 +15,7 @@ script_dir=$(dirname $0)
 source $script_dir/constants.sh
 
 SCRIPT_NAME=$(basename $0)
-DIR_NAME="/opt/seagate/sspl/"
+DIR_NAME="/opt/seagate/sspl"
 RSYSLOG_CONF="/etc/rsyslog.d/0-iemfwd.conf"
 RSYSLOG_SSPL_CONF="/etc/rsyslog.d/1-ssplfwd.conf"
 LOGROTATE_CONF="/etc/logrotate.d/iem_messages"
@@ -74,7 +74,7 @@ config_sspl() {
     product=$(sed -nr 's/^product=([^,]+)$/\1/p' $SSPL_CONF | head -1)
     [ -z "$product" ] && echo "No product specified in $SSPL_CONF" && exit 1
 
-    enabled_products=$(python3.6 $DIR_NAME/low-level/framework/base/sspl_constants.py)
+    enabled_products=$(python3.6 $DIR_NAME/bin/sspl_constants.py)
     [ -z "$enabled_products" ] && echo "No enabled products!" && exit 1
     [[ $enabled_products =~ (^| )$product($| ) ]] || {
         echo "Product '$product' is not in enabled products list: $enabled_products";
@@ -86,9 +86,9 @@ config_sspl() {
 
     # Add sspl-ll user to required groups and sudoers file etc.
     echo "Initializing SSPL configuration ... "
-    /opt/seagate/sspl/low-level/framework/sspl_reinit $product || {
+    $DIR_NAME/bin/sspl_reinit $product || {
         reinit_err="$?";
-        echo -n "/opt/seagate/sspl/low-level/framework/sspl_reinit failed ";
+        echo -n "$DIR_NAME/bin/sspl_reinit failed ";
         echo "with exit code ${reinit_err} for product $product";
         exit 1;
     }
@@ -105,7 +105,7 @@ config_sspl() {
     [ ! -z "$SSPL_LOG_FILE_PATH" ] &&
     {
         sed -i "s|File=.*|File=\"$SSPL_LOG_FILE_PATH\")|g" $RSYSLOG_SSPL_CONF
-        sed -i "1 s|^.*$|${SSPL_LOG_FILE_PATH}|g" /opt/seagate/sspl/low-level/files/etc/logrotate.d/sspl_logs
+        sed -i "1 s|^.*$|${SSPL_LOG_FILE_PATH}|g" $DIR_NAME/conf/etc/logrotate.d/sspl_logs
     }
 
     # IEM configuration
@@ -117,10 +117,10 @@ config_sspl() {
         sed -i "s|File=.*|File=\/var/log/iem/iem_messages\"|g" $RSYSLOG_CONF
     else
         sed -i "s|File=.*|File=\"${LOG_FILE_PATH}\"|g" $RSYSLOG_CONF
-        sed -i "1 s|^.*$|${LOG_FILE_PATH}|g" /opt/seagate/sspl/low-level/files/etc/logrotate.d/iem_messages
+        sed -i "1 s|^.*$|${LOG_FILE_PATH}|g" $DIR_NAME/conf/etc/logrotate.d/iem_messages
     fi
-    cp /opt/seagate/sspl/low-level/files/etc/logrotate.d/iem_messages $LOGROTATE_CONF
-    cp /opt/seagate/sspl/low-level/files/etc/logrotate.d/sspl_logs $LOGROTATE_SSPL_CONF
+    cp $DIR_NAME/conf/etc/logrotate.d/iem_messages $LOGROTATE_CONF
+    cp $DIR_NAME/conf/etc/logrotate.d/sspl_logs $LOGROTATE_SSPL_CONF
 
     # This rsyslog restart will happen after successful updation of rsyslog
     # conf file and before sspl starts. If at all this will be removed from
diff --git a/low-level/framework/sspl_init b/low-level/framework/sspl_init
--- a/low-level/framework/sspl_init
+++ b/low-level/framework/sspl_init
@@ -3,7 +3,7 @@
 set -u -o pipefail
 
 SCRIPT_NAME=$(basename $0)
-DIR_NAME="/opt/seagate/sspl/"
+DIR_NAME="/opt/seagate/sspl"
 SSPL_CONF="/etc/sspl.conf"
 RSYSLOG_CONF="/etc/rsyslog.d/0-iemfwd.conf"
 RSYSLOG_SSPL_CONF="/etc/rsyslog.d/1-ssplfwd.conf"
@@ -125,7 +125,7 @@ create_req() {
 config_sspl() {
 
     # Install packages which are not available in YUM repo, from PIP
-    pip3.6 install -r /opt/seagate/sspl/low-level/requirements.txt
+    pip3.6 install -r /opt/seagate/sspl/conf/requirements.txt
 
     # steps from %post section of sspl-ll.spec
 
@@ -134,10 +134,10 @@ config_sspl() {
 
     # Copy rsyslog configuration
     [ -f /etc/rsyslog.d/0-iemfwd.conf ] ||
-       cp /opt/seagate/sspl/low-level/files/etc/rsyslog.d/0-iemfwd.conf /etc/rsyslog.d/0-iemfwd.conf
+       cp /opt/seagate/sspl/conf/etc/rsyslog.d/0-iemfwd.conf /etc/rsyslog.d/0-iemfwd.conf
 
     [ -f $RSYSLOG_SSPL_CONF ] ||
-       cp /opt/seagate/sspl/low-level/files/$RSYSLOG_SSPL_CONF $RSYSLOG_SSPL_CONF
+       cp /opt/seagate/sspl/conf/$RSYSLOG_SSPL_CONF $RSYSLOG_SSPL_CONF
 
     force=0
     role=
@@ -186,7 +186,7 @@ config_sspl() {
     product=$(sed -nr 's/^product=([^,]+)$/\1/p' $SSPL_CONF | head -1)
     [ -z "$product" ] && echo "No product specified in $SSPL_CONF" && exit 1
 
-    enabled_products=$(python3.6 $DIR_NAME/low-level/framework/base/sspl_constants.py)
+    enabled_products=$(python3.6 $DIR_NAME/bin/sspl_constants.py)
     [ -z "$enabled_products" ] && echo "No enabled products!" && exit 1
     [[ $enabled_products =~ (^| )$product($| ) ]] || {
         echo "Product '$product' is not in enabled products list: $enabled_products";
@@ -201,9 +201,9 @@ config_sspl() {
 
     # Add sspl-ll user to required groups and sudoers file etc.
     echo "Initializing SSPL configuration ... "
-    /opt/seagate/sspl/low-level/framework/sspl_reinit $product || {
+    /opt/seagate/sspl/bin/sspl_reinit $product || {
         reinit_err="$?";
-        echo -n "/opt/seagate/sspl/low-level/framework/sspl_reinit failed ";
+        echo -n "/opt/seagate/sspl/bin/sspl_reinit failed ";
         echo "with exit code ${reinit_err} for product $product";
         exit 1;
     }
@@ -223,9 +223,9 @@ config_sspl() {
 
     # Add required user and vhost to RabbitMQ. Set user permissions etc.
     echo "Creating required RABBITMQ configuration.... "
-    /opt/seagate/sspl/low-level/framework/sspl_rabbitmq_reinit $product || {
+    /opt/seagate/sspl/bin/sspl_rabbitmq_reinit $product || {
         reinit_err="$?";
-        echo -n "/opt/seagate/sspl/low-level/framework/sspl_rabbitmq_reinit failed ";
+        echo -n "/opt/seagate/sspl/bin/sspl_rabbitmq_reinit failed ";
         echo "with exit code ${reinit_err} for product $product";
         exit 1;
     }
@@ -247,7 +247,7 @@ config_sspl() {
     [ ! -z "$SSPL_LOG_FILE_PATH" ] &&
     {
         sed -i "s|File=.*|File=\"$SSPL_LOG_FILE_PATH\")|g" $RSYSLOG_SSPL_CONF
-        sed -i "1 s|^.*$|${SSPL_LOG_FILE_PATH}|g" /opt/seagate/sspl/low-level/files/etc/logrotate.d/sspl_logs
+        sed -i "1 s|^.*$|${SSPL_LOG_FILE_PATH}|g" /opt/seagate/sspl/conf/etc/logrotate.d/sspl_logs
     }
 
 
@@ -260,11 +260,11 @@ config_sspl() {
         sed -i "s|File=.*|File=\/var/log/iem/iem_messages\"|g" $RSYSLOG_CONF
     else
         sed -i "s|File=.*|File=\"${LOG_FILE_PATH}\"|g" $RSYSLOG_CONF
-        sed -i "1 s|^.*$|${LOG_FILE_PATH}|g" /opt/seagate/sspl/low-level/files/etc/logrotate.d/iem_messages
+        sed -i "1 s|^.*$|${LOG_FILE_PATH}|g" /opt/seagate/sspl/conf/etc/logrotate.d/iem_messages
     fi
 
-    cp /opt/seagate/sspl/low-level/files/etc/logrotate.d/iem_messages $LOGROTATE_CONF
-    cp /opt/seagate/sspl/low-level/files/etc/logrotate.d/sspl_logs $SSPL_LOGROTATE_CONF
+    cp /opt/seagate/sspl/conf/etc/logrotate.d/iem_messages $LOGROTATE_CONF
+    cp /opt/seagate/sspl/conf/etc/logrotate.d/sspl_logs $SSPL_LOGROTATE_CONF
 
     # This rsyslog restart will happen after successful updation of rsyslog
     # conf file and before sspl starts. If at all this will be removed from
