EOS-13069 : Disable pyinstaller for easy 3rd party integrations
Signed-off-by: Satish Darade <satish.darade@seagate.com>

diff --git a/low-level/files/opt/seagate/sspl/bin/sspl_config b/low-level/files/opt/seagate/sspl/bin/sspl_config
--- a/low-level/files/opt/seagate/sspl/bin/sspl_config
+++ b/low-level/files/opt/seagate/sspl/bin/sspl_config
@@ -89,7 +89,7 @@ config_sspl() {
     }
 
     # Put minion id, consul_host and consul_port in conf file
-    python3 $DIR_NAME/low-level/framework/utils/salt_util.py $SSPL_CONF;
+    python3 $DIR_NAME/bin/salt_util.py $SSPL_CONF;
 
     [ -f $SSPL_CONFIGURED ] && {
         [ "$force" = "1" ] && ans="y" || ans=;
@@ -105,7 +105,7 @@ config_sspl() {
     product=$(sed -nr 's/^product=([^,]+)$/\1/p' $SSPL_CONF | head -1)
     [ -z "$product" ] && echo "No product specified in $SSPL_CONF" && exit 1
 
-    enabled_products=$(python3.6 $DIR_NAME/low-level/framework/base/sspl_constants.py)
+    enabled_products=$(python3.6 $DIR_NAME/bin/sspl_constants.py)
     [ -z "$enabled_products" ] && echo "No enabled products!" && exit 1
     [[ $enabled_products =~ (^| )$product($| ) ]] || {
         echo "Product '$product' is not in enabled products list: $enabled_products";
@@ -117,9 +117,9 @@ config_sspl() {
 
     # Add sspl-ll user to required groups and sudoers file etc.
     echo "Initializing SSPL configuration ... "
-    $DIR_NAME/low-level/framework/sspl_reinit $product || {
+    $DIR_NAME/bin/sspl_reinit $product || {
         reinit_err="$?";
-        echo -n "$DIR_NAME/low-level/framework/sspl_reinit failed ";
+        echo -n "$DIR_NAME/bin/sspl_reinit failed ";
         echo "with exit code ${reinit_err} for product $product";
         exit 1;
     }
diff --git a/low-level/framework/sspl_init b/low-level/framework/sspl_init
--- a/low-level/framework/sspl_init
+++ b/low-level/framework/sspl_init
@@ -20,7 +20,7 @@ set -u -o pipefail
 SCRIPT_NAME=$(basename $0)
 script_dir=$(realpath $(dirname $0)/..)
 # Import common constants
-. $script_dir/files/opt/seagate/sspl/bin/constants.sh
+source $script_dir/files/opt/seagate/sspl/bin/constants.sh
 DIR_NAME="/opt/seagate/$PRODUCT_FAMILY/sspl"
 SSPL_CONF="/etc/sspl.conf"
 RSYSLOG_CONF="/etc/rsyslog.d/0-iemfwd.conf"
@@ -149,7 +149,7 @@ config_sspl() {
     # steps from %post section of sspl-ll.spec
 
     # Copy sspl conf
-    [ -f /etc/sspl.conf ] || cp /opt/seagate/$PRODUCT_FAMILY/sspl/low-level/files/opt/seagate/sspl/conf/sspl.conf.LDR_R1 /etc/sspl.conf
+    [ -f /etc/sspl.conf ] || cp /opt/seagate/$PRODUCT_FAMILY/sspl/conf/sspl.conf.LDR_R1 /etc/sspl.conf
 
     # Copy rsyslog configuration
     [ -f /etc/rsyslog.d/0-iemfwd.conf ] ||
@@ -205,7 +205,7 @@ config_sspl() {
     product=$(sed -nr 's/^product=([^,]+)$/\1/p' $SSPL_CONF | head -1)
     [ -z "$product" ] && echo "No product specified in $SSPL_CONF" && exit 1
 
-    enabled_products=$(python3.6 $DIR_NAME/low-level/framework/base/sspl_constants.py)
+    enabled_products=$(python3.6 $DIR_NAME/bin/sspl_constants.py)
     [ -z "$enabled_products" ] && echo "No enabled products!" && exit 1
     [[ $enabled_products =~ (^| )$product($| ) ]] || {
         echo "Product '$product' is not in enabled products list: $enabled_products";
@@ -220,9 +220,9 @@ config_sspl() {
 
     # Add sspl-ll user to required groups and sudoers file etc.
     echo "Initializing SSPL configuration ... "
-    $SSPL_BASE_DIR/low-level/framework/sspl_reinit $product || {
+    $SSPL_BASE_DIR/bin/sspl_reinit $product || {
         reinit_err="$?";
-        echo -n "$SSPL_BASE_DIR/low-level/framework/sspl_reinit failed ";
+        echo -n "$SSPL_BASE_DIR/bin/sspl_reinit failed ";
         echo "with exit code ${reinit_err} for product $product";
         exit 1;
     }
@@ -232,9 +232,9 @@ config_sspl() {
 
     # Add required user and vhost to RabbitMQ. Set user permissions etc.
     echo "Creating required RABBITMQ configuration.... "
-    python3 $SSPL_BASE_DIR/low-level/framework/sspl_rabbitmq_reinit $product || {
+    python3 $SSPL_BASE_DIR/bin/sspl_rabbitmq_reinit $product || {
         reinit_err="$?";
-        echo -n "$SSPL_BASE_DIR/low-level/framework/sspl_rabbitmq_reinit failed ";
+        echo -n "$SSPL_BASE_DIR/bin/sspl_rabbitmq_reinit failed ";
         echo "with exit code ${reinit_err} for product $product";
         exit 1;
     }
@@ -246,7 +246,7 @@ config_sspl() {
     touch /etc/mdadm.conf
     setfacl -m u:sspl-ll:rw /etc/mdadm.conf
 
-    cp /opt/seagate/$PRODUCT_FAMILY/sspl/low-level/files/opt/seagate/sspl/conf/sspl-ll.service.$product /etc/systemd/system/sspl-ll.service
+    cp /opt/seagate/$PRODUCT_FAMILY/sspl/conf/sspl-ll.service.$product /etc/systemd/system/sspl-ll.service
     touch $SSPL_CONFIGURED
 
     # SSPL Log file configuration
