EOS-4653: salt-call --local state.apply components.sspl unable to deployed with Centos 7.7
Change-Id: Ifed94371227eea0ffb5956ae0550ccae24a7aa7f

diff --git a/low-level/files/opt/seagate/sspl/bin/sspl_test b/low-level/files/opt/seagate/sspl/bin/sspl_test
--- a/low-level/files/opt/seagate/sspl/bin/sspl_test
+++ b/low-level/files/opt/seagate/sspl/bin/sspl_test
@@ -1,5 +1,8 @@
 #!/bin/bash -e
 
+# Stop the script if any command fails
+set -e -u -o pipefail
+
 TEST_DIR=/opt/seagate/sspl/sspl_test
 if [ ! -d $TEST_DIR ]; then
     echo "sspl-test is not installed. Skipping tests"
