EOS-8860:SSPL:Deploy and start SSPL service without HA in VM environment. (#50)
* Setup ECS with 3 nodes - Alerts are propagated in VM cluster nodes

Signed-off-by: Mariyappan Ponnusamy <mariyappan.ponnusamy@seagate.com>

* Keep the product name as EES

* Update hosts file with defined host name from salt config

Signed-off-by: Mariyappan Ponnusamy <mariyappan.ponnusamy@seagate.com>

diff --git a/low-level/files/opt/seagate/sspl/bin/sspl_provisioner_init b/low-level/files/opt/seagate/sspl/bin/sspl_provisioner_init
--- a/low-level/files/opt/seagate/sspl/bin/sspl_provisioner_init
+++ b/low-level/files/opt/seagate/sspl/bin/sspl_provisioner_init
@@ -10,83 +10,126 @@ set -e -u -o pipefail
 ##############################################################################
 
 SCRIPT_DIR=$(dirname $0)
+SCRIPT_NAME=$(basename $0)
+
 . $SCRIPT_DIR/bin/constants.sh
 
-# Install consul if not available
-if ! [ -x "$(command -v /opt/seagate/$PRODUCT_FAMILY/hare/bin/consul)" ]; then
-    if ! [ -x "$(command -v wget)" ]; then
-        yum install -y wget
-    fi
-    wget https://releases.hashicorp.com/consul/1.7.0/consul_1.7.0_linux_amd64.zip
-    if ! [ -x "$(command -v unzip)" ]; then
-        yum install -y unzip
-    fi
-    unzip consul_1.7.0_linux_amd64.zip
-    mkdir -p /opt/seagate/$PRODUCT_FAMILY/hare/bin
-    mv ./consul /opt/seagate/$PRODUCT_FAMILY/hare/bin/consul
-    rm consul_1.7.0_linux_amd64.zip
-fi
+rmq_cluster=true
+rmq_cluster_nodes=
 
-if ! [ "$(rpm -qa | grep cortx-prvsnr-cli)" ]; then
-    # salt minion config has eosnode-1 as master node name hence adding same in /etc/hosts
-    if ! [ "$(cat /etc/hosts | grep eosnode-1)" ]; then
-        echo "127.0.0.1 eosnode-1" >> /etc/hosts
-    fi
-else
-    # It will remove already installed packages
-    yum remove -y cortx-prvsnr-cli*
-    rm -rf /etc/salt/*
-fi
+usage() {
+    cat << EOF
+    $SCRIPT_NAME
+        [-p|--product-name <EES|ECS>]
+        [-c|--rmq-cluster <true|false>]
+        [-n|--rmq-nodes <name of the nodes>]
+EOF
+    exit 1
+}
 
-# to install updated packages
-pkg_name=$(curl -s http://ci-storage.mero.colo.seagate.com/releases/eos/github/master/rhel-7.7.1908/2629/dev/|grep cortx-prvsnr-cli-1.0.0.*.rpm -o)
-echo $pkg_name
-yum install -y http://ci-storage.mero.colo.seagate.com/releases/eos/github/master/rhel-7.7.1908/2629/dev/$pkg_name
-sudo /opt/seagate/cortx/provisioner/cli/src/setup-provisioner -S http://ci-storage.mero.colo.seagate.com/releases/eos/github/master/rhel-7.7.1908/2629/dev/
-salt-call state.apply components.system
-python3 /opt/seagate/cortx/provisioner/cli/pillar_encrypt
-
-# Start /opt/seagate/<product>/hare/bin/consul if not running
-CONSUL_PS=$(ps -aux | grep "consul" | grep -v "grep" || true)
-[ -z "$CONSUL_PS" ] && /opt/seagate/$PRODUCT_FAMILY/hare/bin/consul agent -dev -config-file=$SCRIPT_DIR/bin/consul_config.json &>/dev/null &
-
-$SCRIPT_DIR/bin/sspl_post_install -p $PRODUCT_NAME -e DEV
-$SCRIPT_DIR/bin/sspl_setup_rabbitmq_cluster
-$SCRIPT_DIR/bin/sspl_setup_init -r $PRODUCT_FAMILY
-$SCRIPT_DIR/bin/sspl_config
-systemctl start rabbitmq-server.service
-systemctl start sspl-ll.service
-
-# TODO: Temporary change until HA integration is in place
-# Switch SSPL to active state to resume all the suspended plugins. If SSPL is
-# not switched to active state then plugins will not respond and tests will
-# fail. Sending SIGUP to SSPL makes SSPL to read state file and switch state.
-TRIES=0
-SSPL_STATUS=$(systemctl show -p ActiveState sspl-ll | sed 's/ActiveState=//g')
-while [ $SSPL_STATUS != "active" ]
-do
-    echo SSPL Service not started. Waiting...
-    sleep 2
-    TRIES=$((TRIES+1))
-    SSPL_STATUS=$(systemctl show -p ActiveState sspl-ll | sed 's/ActiveState=//g')
-    if [ $TRIES -gt 4 ]
-    then
-        break
-    fi
+while getopts ":p:c:n:" OPTION; do
+    case $OPTION in
+        p )
+            PRODUCT_NAME=$OPTARG
+            ;;
+        c )
+            rmq_cluster=$OPTARG
+            ;;
+        n )
+            rmq_cluster_nodes=$OPTARG
+            ;;
+        * )
+            usage
+            ;;
+    esac
 done
 
-if [ $SSPL_STATUS = "active" ]
-then
-    echo SSPL Service started.
-    echo Waiting 5 seconds to initialize.
-    sleep 5
-    echo "*************************************************************************"
-    echo "Changing SSPL state to 'active', disable step once HA integration complete"
-    echo "*************************************************************************"
-    echo "state=active" > /var/$PRODUCT_FAMILY/sspl/data/state.txt
-    PID=`/sbin/pidof -s /usr/bin/sspl_ll_d`
-    kill -s SIGHUP $PID
+[ -z "$rmq_cluster" ] && rmq_cluster=true
+[ -z "$PRODUCT_NAME" ] && PRODUCT_NAME="EES"
+
+setup_provisioner_prereq(){
+    if ! [ "$(rpm -qa | grep cortx-prvsnr-cli)" ]; then
+        # get defined host name from salt minion and update hosts file
+        SRVNODE=
+        [ -f "/etc/salt/minion_id" ] && SRVNODE="$(cat /etc/salt/minion_id)"
+        if [ -n "$SRVNODE" ]; then
+            [ -z "$(cat /etc/hosts | grep $SRVNODE)" ] && echo "127.0.0.1 $SRVNODE" >> /etc/hosts
+        fi
+    else
+        # It will remove already installed packages
+        yum remove -y cortx-prvsnr-cli*
+        rm -rf /etc/salt/*
+    fi
+
+    # to install updated packages
+    pkg_name=$(curl -s http://ci-storage.mero.colo.seagate.com/releases/eos/github/master/rhel-7.7.1908/2629/dev/|grep cortx-prvsnr-cli-1.0.0.*.rpm -o)
+    echo $pkg_name
+    yum install -y http://ci-storage.mero.colo.seagate.com/releases/eos/github/master/rhel-7.7.1908/2629/dev/$pkg_name
+    # provisioner decides the setup(single or dual node) for deployment and
+    # they don't use this dev init script. This script supports only single node setup.
+    sudo /opt/seagate/cortx/provisioner/cli/src/setup-provisioner -S http://ci-storage.mero.colo.seagate.com/releases/eos/github/master/rhel-7.7.1908/2629/dev/
+    salt-call state.apply components.system
+    python3 /opt/seagate/cortx/provisioner/cli/pillar_encrypt
+
+}
+
+
+start_req_services(){
+    [ "$rmq_cluster" == true ] && systemctl start rabbitmq-server.service
+    systemctl start sspl-ll.service
+
+    # TODO: Temporary change until HA integration is in place
+    # Switch SSPL to active state to resume all the suspended plugins. If SSPL is
+    # not switched to active state then plugins will not respond and tests will
+    # fail. Sending SIGUP to SSPL makes SSPL to read state file and switch state.
+    TRIES=0
+    SSPL_STATUS=$(systemctl show -p ActiveState sspl-ll | sed 's/ActiveState=//g')
+    while [ $SSPL_STATUS != "active" ]
+    do
+        echo SSPL Service not started. Waiting...
+        sleep 2
+        TRIES=$((TRIES+1))
+        SSPL_STATUS=$(systemctl show -p ActiveState sspl-ll | sed 's/ActiveState=//g')
+        if [ $TRIES -gt 4 ]
+        then
+            break
+        fi
+    done
+
+    if [ $SSPL_STATUS == "active" -a $PRODUCT_NAME == "ECS" ]
+    then
+        echo SSPL Service started.
+        echo Waiting 5 seconds to initialize.
+        sleep 5
+        echo "*************************************************************************"
+        echo "SSPL state is 'active'"
+        echo "*************************************************************************"
+    elif [ $SSPL_STATUS == "active" -a $PRODUCT_NAME == "EES" ]
+    then
+        echo SSPL Service started.
+        echo Waiting 5 seconds to initialize.
+        sleep 5
+        echo "*************************************************************************"
+        echo "Changing SSPL state to 'active', disable step once HA integration complete"
+        echo "*************************************************************************"
+        echo "state=active" > /var/$PRODUCT_FAMILY/sspl/data/state.txt
+        PID=`/sbin/pidof -s /usr/bin/sspl_ll_d`
+        kill -s SIGHUP $PID
+    else
+        echo SSPL Service not started after 10 seconds.
+        echo Failed to make SSPL state ACTIVE
+    fi
+}
+
+
+setup_provisioner_prereq
+$SCRIPT_DIR/bin/sspl_post_install -p $PRODUCT_NAME -e DEV -c $rmq_cluster
+$SCRIPT_DIR/bin/sspl_setup_init -r $PRODUCT_FAMILY
+if [ "$PRODUCT_NAME" == "ECS" ]; then
+    [ -z "$rmq_cluster_nodes" ] && $SCRIPT_DIR/bin/sspl_config || $SCRIPT_DIR/bin/sspl_config -n $rmq_cluster_nodes
+    [ "$rmq_cluster" == true ] && $SCRIPT_DIR/bin/sspl_setup_rabbitmq_cluster
 else
-    echo SSPL Service not started after 10 seconds.
-    echo Failed to make SSPL state ACTIVE
+    $SCRIPT_DIR/bin/sspl_config
+    $SCRIPT_DIR/bin/sspl_setup_rabbitmq_cluster
 fi
+start_req_services
