COSTOR-559 adding dependent process check for aliveness and dependent rpm checks for config role 'ssu','vm','cmu','gw' 	   removing bash -e option to exit on first error, so can collect required command return value, print debug log & then exit 	   addressing review comments
Change-Id: I54d4d30e7afb5cde8287677b4db30f44c008dc43

diff --git a/low-level/framework/sspl_init b/low-level/framework/sspl_init
--- a/low-level/framework/sspl_init
+++ b/low-level/framework/sspl_init
@@ -1,12 +1,36 @@
 #!/bin/bash
 
-set -eu -o pipefail
+set -u -o pipefail
 
 SCRIPT_NAME=$(basename $0)
 SSPL_CONF="/etc/sspl_ll.conf"
 SSPL_CONFIGURED="/var/sspl/sspl-configured"
 ROLES="gw ssu vm cmu"
 
+SSU_DEPENDENCY_RPMS=(
+                "epel-release"
+                "sg3_utils"
+                "puppet"
+                "gemhpi"
+                "pull_sea_logs"
+                "python-hpi"
+                "zabbix-agent-lib"
+                "zabbix-api-gescheit"
+                "zabbix-xrtx-lib"
+                "python-openhpi-baselib"
+                "zabbix-collector"
+     )
+
+SSU_REQUIRED_PROCESSES=(
+                "openhpid"
+                "dcs-collectord"
+                )
+
+VM_DEPENDENCY_RPMS=(
+                "epel-release"
+                "puppet"
+                "lxqt-policykit"
+                )
 usage() {
     cat << EOF
 $SCRIPT_NAME [{check|config [-f] [-r <ssu|gw|cmu|vm>]]
@@ -17,6 +41,60 @@ config options:
 
 EOF
     exit 1
+}
+
+check_for_dep_rpms() {
+
+   rpms=("$@");
+
+   for rpm in "${rpms[@]}"; do
+        rpm -q --quiet $rpm;
+
+        if [ $? -eq 1 ]; then
+          echo "- Required rpm '$rpm' not installed, exiting";
+          exit 1;
+        fi
+   done
+}
+
+check_for_active_processes() {
+
+   processes=("$@");
+
+   for proc in "${processes[@]}"; do
+        pgrep -x $proc > /dev/null;
+
+        if [ $? -eq 1 ]; then
+            echo "- Required process '$proc' not running, exiting";
+            exit 1;
+        fi
+   done
+
+}
+
+check_dependencies() {
+
+    # Check for dependency rpms and required processes active state based on role
+    case $1 in
+       "ssu")
+              echo "Checking for dependency rpms for role '$1'";
+              check_for_dep_rpms "${SSU_DEPENDENCY_RPMS[@]}";
+
+              echo "Checking for required processes running state for role '$1'";
+              check_for_active_processes "${SSU_REQUIRED_PROCESSES[@]}";
+              ;;
+
+       "vm"|"gw"|"cmu")
+              echo "Checking for dependency rpms for role '$1'";
+              check_for_dep_rpms "${VM_DEPENDENCY_RPMS[@]}";
+
+              # No processes to check in vm/gw/cmu env
+              ;;
+
+       *)
+              echo -e "No rpm or process dependencies set, to check for supplied role '$1', skipping checks.\n";
+              ;;
+    esac
 }
 
 config_sspl() {
@@ -65,6 +143,9 @@ config_sspl() {
 
     # Configure role
     [ -z "$role" ] || sed -i "s/^setup=.*/setup=$role/g" $SSPL_CONF
+
+    # Check for sspl required processes and misc dependencies like installation,etc based on 'role'
+    [ -z "$role" ] || check_dependencies $role
 
     # Add sspl-ll user to required groups and sudoers file etc.
     echo "Initializing SSPL configuration ... "
