EOS-16240 : SSPL Module-Remove-insert-pythonpath-code

diff --git a/low-level/framework/sspl_init b/low-level/framework/sspl_init
--- a/low-level/framework/sspl_init
+++ b/low-level/framework/sspl_init
@@ -217,9 +217,9 @@ config_sspl() {
 
     # Add sspl-ll user to required groups and sudoers file etc.
     echo "Initializing SSPL configuration ... "
-    $SSPL_BASE_DIR/bin/sspl_reinit $product || {
+    $SSPL_BASE_DIR/low-level/framework/sspl_reinit $product || {
         reinit_err="$?";
-        echo -n "$SSPL_BASE_DIR/bin/sspl_reinit failed ";
+        echo -n "$SSPL_BASE_DIR/low-level/framework/sspl_reinit failed ";
         echo "with exit code ${reinit_err} for product $product";
         exit 1;
     }
@@ -229,9 +229,9 @@ config_sspl() {
 
     # Add required user and vhost to RabbitMQ. Set user permissions etc.
     echo "Creating required RABBITMQ configuration.... "
-    python3 $SSPL_BASE_DIR/bin/sspl_rabbitmq_reinit $product || {
+    python3 $SSPL_BASE_DIR/low-level/framework/sspl_rabbitmq_reinit.py $product || {
         reinit_err="$?";
-        echo -n "$SSPL_BASE_DIR/bin/sspl_rabbitmq_reinit failed ";
+        echo -n "$SSPL_BASE_DIR/low-level/framework/sspl_rabbitmq_reinit.py failed ";
         echo "with exit code ${reinit_err} for product $product";
         exit 1;
     }
